### ISSUE TITLE
axisecp/acap-sdk:3.5-aarch64 Docker image does not have OpenCL

### ISSUE THREAD

**Issue by dtsmith2001** [AxisCommunications/acap-computer-vision-sdk#25]
> **Please do not disclose security vulnerabilities as issues. See our [security policy](../../SECURITY.md) for responsible disclosures.**

### Describe the bug

I pulled `axisecp/acap-sdk:3.5-aarch64` but it does not contain `/axis/opencl`.

```
root@1c6d5ea358db:/# ls -la /axis/opencl
ls: cannot access '/axis/opencl': No such file or directory
root@1c6d5ea358db:/# 
```

### To reproduce

Please provide as much context as possible and describe the *reproduction steps* that someone else can follow to recreate the issue on their own.

A team member will try to reproduce the issue with your provided steps. If there are no reproduction steps or no obvious way to reproduce the issue, the team will ask you for those steps. Bugs without steps will not be addressed until they can be reproduced.

1. ```docker pull axisecp/acap-computer-vision-sdk:latest-armv7hf-devel```
2. ```docker run --rm -it axisecp/acap-computer-vision-sdk:latest-armv7hf-devel```
3. ```ls -la /axis/opencl```

### Environment

N/A

**Comment by marbali8** [comment]
Hello,
Could you explain what do you want to do? In the bug description, you mention pulling a Docker image different from what you mention in the reproduction steps. 

Thank you.

**Comment by Corallo** [comment]
OpenCL is now available also for aarch64 in both native-sdk and computer-vision-sdk, please make sure to use the latest version of the sdk.
Closing the issue.
