### ISSUE TITLE
Standard lib sqlite3 is broken in the Python installation in the SDK

### ISSUE THREAD

**Issue by daniel-falk** [AxisCommunications/acap-computer-vision-sdk#32]
### Describe the bug
The python installation that is found in `Computer Vision SDK 4` is missing the shared libraries for the standard module `sqlite3` in Python3. This has been the case ever since SDK release 1.1 of `Computer Vision SDK 4` for all platforms.

Since the `sqlite3` module is broken it is not possible to use e.g. `IPython` in the camera. As a work around, the two shared objects can be copied from another compatible Python installation:
```bash
FROM arm64v8/python:3.8-slim-bullseye as python-fix-aarch64
FROM arm32v7/python:3.8-slim-bullseye as python-fix-armv7hf
FROM python-fix-${ARCH} as python-fix

FROM ${REPO}/acap-computer-vision-sdk:${SDK_VERSION}-${ARCH} AS cv-sdk
FROM runtime-image-${ARCH}

# Copy the Axis python build from the SDK
COPY --from=cv-sdk /axis/python /

# Fix the broken python installation from Axis by copying the sqlite3
# shared library from a working python installation for the same
# platform
COPY --from=python-fix /usr/local/lib/python3.8/lib-dynload/_sqlite3.*.so ./usr/lib/python3.8/lib-dynload/
RUN apt update && apt install -y --no-install-recommends libsqlite3-dev && rm -rf /var/lib/apt/lists/*
```
Instead of apt-installing `libsqlite3-dev` one could instead copy `libsqlite3.so` from the `python-fix` image.

### To reproduce
The issue can be reproduced e.g. in the `hello-world` example of `acap-computer-vision-sdk-examples`:

```bash
docker build . -t py-cam
docker run -it --rm --privileged multiarch/qemu-user-static --credential yes --persistent yes
docker run --rm -it --entrypoint /usr/bin/python3 py-cam -c "import sqlite3"
```
output:
```
WARNING: The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/amd64) and no specific platform was requested
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/lib/python3.8/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
```

As can be seen, the so-files are missing from all versions of the `Computer Vision SDK 4`:
```bash
daniel@fixedIT hello-world $ docker run --rm -it axisecp/acap-computer-vision-sdk:1.3-aarch64 find / -name '*sqlite3*'
/axis/python/usr/lib/python3.8/sqlite3
daniel@fixedIT hello-world $ docker run --rm -it axisecp/acap-computer-vision-sdk:1.2-aarch64 find / -name '*sqlite3*'
/axis/python/usr/lib/python3.8/sqlite3
daniel@fixedIT hello-world $ docker run --rm -it axisecp/acap-computer-vision-sdk:1.1-aarch64 find / -name '*sqlite3*'
/axis/python/usr/lib/python3.8/sqlite3
```

Behavior is also the same if pushing the image to the camera and running it there.

**Comment by daniel-falk** [comment]
@mikaelli-axis Hi Mikael, do you know if anyone has looked at this? It does not seem like anyone is assigned to the issue.

The problem seems to be the same in Computer Vision SDK 1.4. Easiest way to replicate it is probably:
```Dockerfile
FROM axisecp/acap-computer-vision-sdk:1.4-aarch64 as sdk

FROM arm64v8/ubuntu:jammy

COPY --from=sdk /axis/python /

CMD ["python3", "-c", "import sqlite3"]
```

```bash
docker build . -t sqlite-test && docker run --rm -it sqlite-test
```

**Comment by mikaelli-axis** [comment]
Hi Daniel, thanks for bringing this to our attention. I'll see who can look into this but as it is right now, if you know a way to solve it (I'm seeing something like this in your first post), maybe you could open a PR? We're not using sqlite ourselves for anything so not sure when we can prioritise fixing it. 

We are, however, looking into how to make the SDK more compatible with apt- and pip-installed packages in general (the copying strategy we're using right now is not great), which might resolve the issue.

**Comment by Corallo** [comment]
Hi @daniel-falk 

Thanks for your contribution!

I'm going to reply partially, maybe @mikaelli-axis can add to it.
Ideally, yes, we would like to change the way we install the python libraries. 
The way we do it now, copying them, creates problems with pip, as it is not aware of the presence of the libraries.
[Causing this kind of issues.](https://github.com/AxisCommunications/acap-computer-vision-sdk-examples/issues/90)

We plan at some point to work to make the installation of python libraries simpler, the biggest obstacle is the installation of opencv that has to be done using the axis-vdo library to collect the frames, which prevent us to just install python and pip in the app.

**Comment by daniel-falk** [comment]
@Corallo OK, I see. If building python wheels instead in the SDK which can be installed from the runtime container, then that problem would be solved. This does however introduce a new complexity in how to distribute the system dependencies which are copied at the same time as the python packages now.. It could also make the image larger unless squashed since the wheel needs to be copied before installing.

Solving the issues above would however only resolve the [#90](https://github.com/AxisCommunications/acap-computer-vision-sdk-examples/issues/90) issues for the aarch64 architecture, for 32 bit arm there are no prebuilt wheels on pypi for neither `shapely` nor `pandas`. This means that they have to be built and both of them depend on the source code for `numpy` at build time.

For `aarch64` this diff to the SDK and bumping the `numpy` version to `1.20.3` as needed by `pandas` makes it possible to simply `pip install` both `pandas` and `shapely`:
```diff
From ad6446b97957fa4dbabd3d22dfcc0269cfe9f39a Mon Sep 17 00:00:00 2001
From: Daniel Falk <daniel.falk.1@fixedit.ai>
Date: Mon, 9 Jan 2023 14:08:55 +0100
Subject: [PATCH] wip

---
 sdk/Dockerfile.aarch64 | 5 +++++
 1 file changed, 5 insertions(+)

diff --git a/sdk/Dockerfile.aarch64 b/sdk/Dockerfile.aarch64
index 447ccb9..c3aeaf1 100644
--- a/sdk/Dockerfile.aarch64
+++ b/sdk/Dockerfile.aarch64
@@ -303,6 +303,8 @@ RUN mkdir -p ${BUILD_ROOT}/python-numpy-deps
 RUN apt-get install --reinstall --download-only -o=dir::cache=${BUILD_ROOT}/python-numpy-deps -y --no-install-recommends \
     libgfortran5
 RUN for f in ${BUILD_ROOT}/python-numpy-deps/archives/*.deb; do dpkg -x $f $TARGET_ROOT; done
+RUN CC="gcc -I$BUILD_ROOT/usr/include -I$BUILD_ROOT/usr/include/$(cat /tmp/python_version) $ARCH_CFLAGS" python3 setup.py bdist_wheel
+
 
 # Build SciPy with OpenBLAS
 FROM build-base-arm AS build-python-scipy
@@ -569,6 +571,7 @@ EOF
 FROM ubuntu:${UBUNTU_VERSION} AS packages
 ARG SDK_ROOT_DIR
 ARG TARGET_ROOT
+ARG BUILD_ROOT
 RUN mkdir -p $SDK_ROOT_DIR
 COPY --from=build-openblas $TARGET_ROOT $SDK_ROOT_DIR/openblas
 COPY --from=build-opencv $TARGET_ROOT $SDK_ROOT_DIR/opencv
@@ -579,6 +582,8 @@ COPY --from=build-python-tfserving $TARGET_ROOT $SDK_ROOT_DIR/python-tfserving
 COPY --from=build-python-scipy $TARGET_ROOT $SDK_ROOT_DIR/python-scipy
 COPY --from=build-tesseract $TARGET_ROOT $SDK_ROOT_DIR/tesseract
 
+COPY --from=build-python-numpy $BUILD_ROOT/numpy/dist/ $SDK_ROOT_DIR/wheels/
+
 # Get OpenCL-related libs from the Native SDK
 FROM build-base AS build-opencl-devel
 ARG AXIS_ARCH
-- 
2.25.1
```

This Dockerfile can then be built with no errors:
```dockerfile
FROM sdk-homebrew:runtime-wheel-aarch64 AS cv-sdk

FROM arm64v8/ubuntu:22.04
COPY --from=cv-sdk /axis/python /
COPY --from=cv-sdk /axis/wheels /wheels
COPY --from=cv-sdk /axis/python-numpy/usr/lib/* /usr/lib/

RUN pip install /wheels/numpy*.whl

RUN pip install requests
RUN pip install jsonpickle
RUN pip install shapely
RUN pip install pandas
```

After this the `numpy` version built with `openblas` is still installed:
```bash
daniel@daniel-desktop:~/src/acap-computer-vision-sdk/sdk$ docker run --rm -it acap-runtime:wheel pip freeze
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
certifi==2022.12.7
charset-normalizer==2.1.1
idna==3.4
jsonpickle==3.0.1
numpy @ file:///wheels/numpy-1.20.3-cp38-cp38-linux_aarch64.whl
pandas==1.5.2
python-dateutil==2.8.2
pytz==2022.7
requests==2.28.1
shapely==2.0.0
six==1.16.0
urllib3==1.26.13
```

and executes fine on the camera:
```bash
daniel@daniel-desktop:~/src/acap-computer-vision-sdk/sdk$ docker --host tcp://192.168.0.91:2375 run --rm -it acap-runtime:wheel python3 -c "import pandas as pd; import numpy as np; print(pd.DataFrame(np.random.random((3,3))))"
          0         1         2
0  0.517681  0.105350  0.455187
1  0.335135  0.165883  0.432602
2  0.616610  0.108417  0.875304
```

**Comment by Corallo** [comment]
This looks good! Thanks for your input!

Yes! It is probably the best to move to pip/wheels for installation, to make things easier even if it comes at the cost of some extra space, we are not really space restricted with SD cards.
We actually noticed once that the version built by us of NumPy is slower than the one that we get from pip for some reason (on aarch64). I think we might be using the 32bit version of openblas or something similar, never investigated deeper. This speaks for just using the pre-built wheels from pip whenever it is possible.

So, for aarch64 the only wheel that we must build is the custom opencv that has access to the capturing service of the camera, the rest could be installed directly from pip without building any other wheels.

For armv7hf we could build the wheels for numpy and some of the other libs that are not supported, but that might be quite some work to maintain them. I don't think we will support pandas for now.

Thanks again for your contribution to our repos!

**Comment by daniel-falk** [comment]
Thanks. Actually I am not too happy about distributing the built python packages as docker images. Other packages often have limiting restrictions on the versions of the libraries needed, such as `pandas` dependency on `numpy` in this case. As it is now this means that I have to rebuild the full SDK (or rather all stages after the one that builds `numpy`) which is a really slow build..

I think that it would be better to distribute the packages using a `pypi` server, then you can have the most common versions of the libraries you support. I understand that the issue with this is that you will get a massive test matrix (increasing exponentially with the number of libraries), but perhaps you could have two different categories of packages:
- Fully supported: Basically what you have now, a few that you test thoroughly together
- Unstable: Common libraries built with a few different versions, only tested in isolation

To support custom requirements you could have the open source docker images with the code needed to build the libraries you have uploaded to your pypi. This would make it easy for me to build e.g. `pandas` by expanding the `build-python-numpy` image from your repo. I think that having each package as a separate docker file would make this easier. If you also have the source distributions uploaded to the `pypi` server, then that might be enough sometime to build another library with build-time dependency on the source of another package.

The packages can be built to wheels, then I can choose if I want to have my own `pypi` server for my own libraries or if I just want to keep them on a NAS/artifactory as `.whl` files.

**Comment by Corallo** [comment]
Yes, using a pypi server would be the best.
And yes, the concept of the computer vision sdk might have to be rethought into something that builds parts like python/opencv, while the wheels are build by other "optional" components.

We are considering to do it, but on the long run, it is quite some work to do all this refactoring.
